spring.application.name=recrutationtask

logging.level.root=DEBUG
logging.level.com.bopielka.recrutationtask=DEBUG

# Disable the embedded web server. This is a CLI application
spring.main.web-application-type=none

# JSONPlaceholder base URL
post.api.base-url=https://jsonplaceholder.typicode.com

# Base directory for exports. Each run creates a timestamped subfolder inside
post.export.directory=posts
